# pubspec.yaml
name: jbm_escpos
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^3.3.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.3.0
  device_info_plus: ^11.0.0
  package_info_plus: ^8.1.0
  flutter_blue_plus: ^1.32.7
  usb_serial: ^0.5.1
  network_info_plus: ^5.0.3
  permission_handler: ^11.3.1
  receive_sharing_intent: ^1.8.0
  encrypt: ^5.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true